// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerGameData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RogueStore {

  /// <summary>Holder for reflection information generated from PlayerGameData.proto</summary>
  public static partial class PlayerGameDataReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerGameData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerGameDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQbGF5ZXJHYW1lRGF0YS5wcm90bxIKUm9ndWVTdG9yZSJMCg5QbGF5ZXJH",
            "YW1lRGF0YRINCgVDb2lucxgBIAEoBRITCgtVbmxvY2tlZElkcxgCIAMoBRIW",
            "Cg5DdXJyZW50Q2xvdGhlcxgDIAMoBUIUSANaEGV4YW1wbGUuY29tO21haW5i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RogueStore.PlayerGameData), global::RogueStore.PlayerGameData.Parser, new[]{ "Coins", "UnlockedIds", "CurrentClothes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerGameData : pb::IMessage<PlayerGameData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerGameData> _parser = new pb::MessageParser<PlayerGameData>(() => new PlayerGameData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerGameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RogueStore.PlayerGameDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerGameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerGameData(PlayerGameData other) : this() {
      coins_ = other.coins_;
      unlockedIds_ = other.unlockedIds_.Clone();
      currentClothes_ = other.currentClothes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerGameData Clone() {
      return new PlayerGameData(this);
    }

    /// <summary>Field number for the "Coins" field.</summary>
    public const int CoinsFieldNumber = 1;
    private int coins_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Coins {
      get { return coins_; }
      set {
        coins_ = value;
      }
    }

    /// <summary>Field number for the "UnlockedIds" field.</summary>
    public const int UnlockedIdsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_unlockedIds_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> unlockedIds_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> UnlockedIds {
      get { return unlockedIds_; }
    }

    /// <summary>Field number for the "CurrentClothes" field.</summary>
    public const int CurrentClothesFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_currentClothes_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> currentClothes_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> CurrentClothes {
      get { return currentClothes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerGameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerGameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Coins != other.Coins) return false;
      if(!unlockedIds_.Equals(other.unlockedIds_)) return false;
      if(!currentClothes_.Equals(other.currentClothes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Coins != 0) hash ^= Coins.GetHashCode();
      hash ^= unlockedIds_.GetHashCode();
      hash ^= currentClothes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Coins != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Coins);
      }
      unlockedIds_.WriteTo(output, _repeated_unlockedIds_codec);
      currentClothes_.WriteTo(output, _repeated_currentClothes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Coins != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Coins);
      }
      unlockedIds_.WriteTo(ref output, _repeated_unlockedIds_codec);
      currentClothes_.WriteTo(ref output, _repeated_currentClothes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Coins != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Coins);
      }
      size += unlockedIds_.CalculateSize(_repeated_unlockedIds_codec);
      size += currentClothes_.CalculateSize(_repeated_currentClothes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerGameData other) {
      if (other == null) {
        return;
      }
      if (other.Coins != 0) {
        Coins = other.Coins;
      }
      unlockedIds_.Add(other.unlockedIds_);
      currentClothes_.Add(other.currentClothes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Coins = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            unlockedIds_.AddEntriesFrom(input, _repeated_unlockedIds_codec);
            break;
          }
          case 26:
          case 24: {
            currentClothes_.AddEntriesFrom(input, _repeated_currentClothes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Coins = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            unlockedIds_.AddEntriesFrom(ref input, _repeated_unlockedIds_codec);
            break;
          }
          case 26:
          case 24: {
            currentClothes_.AddEntriesFrom(ref input, _repeated_currentClothes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
